export const FETCH_RECENTLY_PLAYED = 'FETCH_RECENTLY_PLAYED'
export const FETCH_RECENTLY_PLAYED_SUCCESS = 'FETCH_RECENTLY_PLAYED_SUCCESS'
export const FETCH_RECENTLY_PLAYED_ERROR = 'FETCH_RECENTLY_PLAYED_ERROR'